# Project name - used as package identifier (must be lowercase, no spaces)
# This is how you'll import your app in other files: import 'package:campuskey/main.dart'
name: campuskey

# Project description - brief explanation of what the app does
description: "Simple CampusKey App"

# Version information - required for iOS builds
version: 1.0.0+1

# Environment section - defines Dart SDK version requirements
environment:
  # SDK constraint - app requires Dart SDK version 3.0.0 or higher, but less than 4.0.0
  # This ensures compatibility with Flutter framework
  sdk: '>=3.0.0 <4.0.0'

# Dependencies section - external packages your app needs to run
dependencies:
  # Flutter SDK - core Flutter framework (always required)
  flutter:
    sdk: flutter
  # HTTP package - used for making API calls to backend server
  # Version ^1.1.0 means 1.1.0 or higher, but less than 2.0.0
  http: ^1.1.0

# Development dependencies - packages only needed during development/testing
dev_dependencies:
  # Flutter test framework - used for writing and running tests
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets for the application
  # These directories contain images, icons, and other static files
  # Files in these folders can be accessed using Image.asset('assets/images/logo.png')
  assets:
    - assets/images/  # Directory for image files (logos, photos, etc.)
    - assets/icons/   # Directory for icon files

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
